site_name: Welcome to MkLorumAB
site_url: https://example.com
theme:
  name: material
  palette: 
    scheme: slate
    primary: red
    accent: indigo
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      options:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
  

